name: My cool workflow

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
    myfirstjob:
              name: First job
              runs-on: macos-latest
              steps:
              - name: Step One
                uses: actions/checkout@v3
              - name: Step Two
                run: |
                  touch ${{ secrets.MY_SECRET.yaml }}
                  touch newfile.yaml
                  echo "Example" >> newfile.yaml
                  cat newfile.yaml
                  pwd
    mysecondjob:
              needs: [myfirstjob]
              name: Second job
              runs-on: macos-latest
              steps:
              - name: Step One
                run: date
    mythirdjob:
              name: Third job
              runs-on: macos-latest
              steps:
              - name: Step One
                run: date
